- hosts: all

  tasks:

    - name: Prune non-dangling, and dangling images
      community.docker.docker_prune:
        containers: false
        images: true
        images_filters:
          dangling: false
        networks: false
        volumes: false
        builder_cache: false
    - name: Prune containers older than 24h
      community.docker.docker_prune:
        containers: true
        containers_filters:
        # only consider containers created more than 24 hours ago
          until: 24h
